# Copyright 2022 Kubespider
# SPDX-License-Identifier: Apache-2.0

name: Kubespider latest image build for DockerHub and AliyunHub

on:
  push:
    branches:
      - nightly

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set Up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Kubespider - build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: cesign/kubespider:nightly
          build-args: |
            GIT_COMMIT=${GITHUB_SHA}

      - name: youget-downloader - build and push
        uses: docker/build-push-action@v3
        with:
          context: ./downloaders/you-get/
          file: ./downloaders/you-get/Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: cesign/youget-downloader:nightly

      - name: ytdlp-downloader - build and push
        uses: docker/build-push-action@v3
        with:
          context: ./downloaders/yt-dlp/
          file: ./downloaders/yt-dlp/Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: cesign/ytdlp-downloader:nightly

      - name: tiktokdlp-downloader - build and push
        uses: docker/build-push-action@v3
        with:
          context: ./downloaders/tiktok-dlp/
          file: ./downloaders/tiktok-dlp/Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: cesign/tiktok-dlp:nightly

      - name: yutto-downloader - build and push
        uses: docker/build-push-action@v3
        with:
          context: ./downloaders/yutto/
          file: ./downloaders/yutto/Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: cesign/yutto-downloader:nightly

  acr-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set Up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ACR
        uses: aliyun/acr-login@v1
        with:
          login-server: https://registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Kubespider - build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          platforms: |
            linux/amd64
          push: true
          tags: registry.cn-hangzhou.aliyuncs.com/jwcesign/kubespider:nightly
          build-args: |
            GIT_COMMIT=${GITHUB_SHA}

      - name: youget-downloader - build and push
        uses: docker/build-push-action@v3
        with:
          context: ./downloaders/you-get/
          file: ./downloaders/you-get/Dockerfile
          platforms: |
            linux/amd64
          push: true
          tags: registry.cn-hangzhou.aliyuncs.com/jwcesign/youget-downloader:nightly

      - name: ytdlp-downloader - build and push
        uses: docker/build-push-action@v3
        with:
          context: ./downloaders/yt-dlp/
          file: ./downloaders/yt-dlp/Dockerfile
          platforms: |
            linux/amd64
          push: true
          tags: registry.cn-hangzhou.aliyuncs.com/jwcesign/ytdlp-downloader:nightly

      - name: tiktokdlp-downloader - build and push
        uses: docker/build-push-action@v3
        with:
          context: ./downloaders/tiktok-dlp/
          file: ./downloaders/tiktok-dlp/Dockerfile
          platforms: |
            linux/amd64
          push: true
          tags: registry.cn-hangzhou.aliyuncs.com/jwcesign/tiktok-dlp:nightly

      - name: yutto-downloader - build and push
        uses: docker/build-push-action@v3
        with:
          context: ./downloaders/yutto/
          file: ./downloaders/yutto/Dockerfile
          platforms: |
            linux/amd64
          push: true
          tags: registry.cn-hangzhou.aliyuncs.com/jwcesign/yutto-downloader:nightly
