# Copyright 2022 Kubespider
# SPDX-License-Identifier: Apache-2.0

name: Kubespider latest image build for DockerHub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Kubespider - build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: cesign/kubespider:latest

    - name: youget-downloader - build and push
      uses: docker/build-push-action@v3
      with:
        context: ./downloaders/you-get/
        push: true
        tags: cesign/youget-downloader:latest

    - name: ytdlp-downloader - build and push
      uses: docker/build-push-action@v3
      with:
        context: ./downloaders/you-get/
        push: true
        tags: cesign/ytdlp-downloader:latest
